name: Publish Docker Image
on:
  push:
    branches:
      - main
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    concurrency:
      group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}: ${{ matrix.dockerfile }}'
      cancel-in-progress: true
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            images: |
              ghcr.io/talavis/snacka-scs
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Github Container Repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # will run as the user who triggered the action, using its token
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.images }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=long
      - name: Build and publish
        uses: docker/build-push-action@v6
        id: build-and-publish
        with:
          file: ${{ matrix.dockerfile }}
          context: .
          push: true
          build-args: version=${{ github.ref_name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
